<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "support_messages".
 *
 * @property int $Id
 * @property int $user_id
 * @property string $message
 * @property int $whn
 */
class SupportMessage extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'support_messages';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'message'], 'required'],
            [['user_id', 'whncrt'], 'integer'],
            [['message'], 'string'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'Id' => 'ID',
            'user_id' => 'User ID',
            'message' => 'Message',
            'whn' => 'Whn',
        ];
    }

    public function getAutor(){
        return $this->hasOne(User::className(),['id'=>'user_id']);
    }

    public function beforeSave($insert)
    {
        $this->whncrt = time();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function getWhn(){
        return date('H:i, d.m.Y', $this->whncrt);
    }


}
