<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "user_balance".
 *
 * @property int $id
 * @property int $user_id
 * @property float $val
 * @property string $whn
 */
class UserBalance extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user_balance';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'val', 'whn'], 'required'],
            [['user_id'], 'integer'],
            [['val'], 'number'],
            [['whncrt'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'Пользователь',
            'val' => 'Количество',
            'whn' => 'Когда',
        ];
    }

    public function getWhn(){
        return date('d.m.Y', $this->whncrt);
    }

    public function beforeSave($insert)
    {
        $this->whncrt = time();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
