<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "user_info".
 *
 * @property int $user_id
 * @property int|null $type_id
 * @property string|null $fio
 * @property string|null $avatar
 * @property string|null $phone
 */
class UserInfo extends \yii\db\ActiveRecord
{
    const TYPES = [
        '1'=>"Клиент",
        '2'=>"Мастер",
        '3'=>"Фирма",
        '10'=>"Админ",
        '11'=>"Модератор",
    ];
    const IMG_URL = 'uploads/';
    const BASE_AVATAR = "/images/avatar.png";

    public $newavatar;
    public $newdoc1;
    public $newdoc2;
    public $newdoc3;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user_info';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id'], 'required'],
            [['user_id', 'type_id', 'city_id'], 'integer'],
            [['fio'], 'string', 'max' => 100],
            [['avatar'], 'string', 'max' => 500],
            [['phone'], 'string', 'max' => 20],
            [['newdoc1'], 'safe'],
            [['doc1'], 'safe'],
            [['balance'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'user_id' => 'User ID',
            'type_id' => 'Тип',
            'fio' => 'ФИО',
            'avatar' => 'Avatar',
            'phone' => 'Телефон',
            'city_id' => 'Город',
        ];
    }

    public function getType(){
        return self::TYPES[$this->type_id];
    }

    public function beforeSave($insert)
    {
        if ($this->newavatar) {
            $this->avatar = self::IMG_URL . $this->user_id . '__avatar.' . $this->newavatar->extension;
            $this->newavatar->saveAs($this->avatar, true);
        }

        if ($this->newdoc1) {
            $this->doc1 = self::IMG_URL . $this->user_id . '__doc1.' . $this->newdoc1->extension;
            $this->newdoc1->saveAs($this->doc1);
        }
        if ($this->newdoc2) {
            $this->doc2 = self::IMG_URL . $this->user_id . '__doc2.' . $this->newdoc2->extension;
            $this->newdoc2->saveAs($this->doc2);
        }
        if ($this->newdoc1) {
            $this->doc3 = self::IMG_URL . $this->user_id . '__doc3.' . $this->newdoc3->extension;
            $this->newdoc3->saveAs($this->doc3);
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function getCity(){
        return $this->hasOne(City::className(),['id'=>'city_id']);
    }
}
